// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package registry_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitRequest struct {
	RepositoryUrl        string   `protobuf:"bytes,1,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetRepositoryUrl() string {
	if m != nil {
		return m.RepositoryUrl
	}
	return ""
}

type InitResponse struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *InitResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetRequest struct {
	SchemaUrl            string   `protobuf:"bytes,1,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetSchemaUrl() string {
	if m != nil {
		return m.SchemaUrl
	}
	return ""
}

type GetResponse struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type StatusRequest struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Lockfile             []byte   `protobuf:"bytes,2,opt,name=lockfile,proto3" json:"lockfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *StatusRequest) GetLockfile() []byte {
	if m != nil {
		return m.Lockfile
	}
	return nil
}

type StatusResponse struct {
	Warnings             []*Warning `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{5}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetWarnings() []*Warning {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type CommitRequest struct {
	SchemaUrl            string   `protobuf:"bytes,1,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{6}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetSchemaUrl() string {
	if m != nil {
		return m.SchemaUrl
	}
	return ""
}

func (m *CommitRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CommitRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type CommitResponse struct {
	Schema               *Schema    `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Warnings             []*Warning `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{7}
}

func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (m *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(m, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

func (m *CommitResponse) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CommitResponse) GetWarnings() []*Warning {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type Warning struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Warning) Reset()         { *m = Warning{} }
func (m *Warning) String() string { return proto.CompactTextString(m) }
func (*Warning) ProtoMessage()    {}
func (*Warning) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{8}
}

func (m *Warning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Warning.Unmarshal(m, b)
}
func (m *Warning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Warning.Marshal(b, m, deterministic)
}
func (m *Warning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Warning.Merge(m, src)
}
func (m *Warning) XXX_Size() int {
	return xxx_messageInfo_Warning.Size(m)
}
func (m *Warning) XXX_DiscardUnknown() {
	xxx_messageInfo_Warning.DiscardUnknown(m)
}

var xxx_messageInfo_Warning proto.InternalMessageInfo

func (m *Warning) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *Warning) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Schema struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Origin               string            `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Lockfile             []byte            `protobuf:"bytes,3,opt,name=lockfile,proto3" json:"lockfile,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{9}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Schema) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Schema) GetLockfile() []byte {
	if m != nil {
		return m.Lockfile
	}
	return nil
}

func (m *Schema) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "registry.v1.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "registry.v1.InitResponse")
	proto.RegisterType((*GetRequest)(nil), "registry.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "registry.v1.GetResponse")
	proto.RegisterType((*StatusRequest)(nil), "registry.v1.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "registry.v1.StatusResponse")
	proto.RegisterType((*CommitRequest)(nil), "registry.v1.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "registry.v1.CommitResponse")
	proto.RegisterType((*Warning)(nil), "registry.v1.Warning")
	proto.RegisterType((*Schema)(nil), "registry.v1.Schema")
	proto.RegisterMapType((map[string]string)(nil), "registry.v1.Schema.MetadataEntry")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6b, 0x14, 0x31,
	0x14, 0x65, 0x76, 0xea, 0x74, 0xf7, 0x4e, 0x77, 0x91, 0x58, 0x34, 0x8e, 0x08, 0x6b, 0x40, 0x58,
	0x28, 0x2c, 0xba, 0xfa, 0x50, 0x5a, 0x44, 0x54, 0xa4, 0xf8, 0x20, 0xe8, 0x14, 0x51, 0x7c, 0x91,
	0xb8, 0xa6, 0xdb, 0xb0, 0x33, 0x93, 0x35, 0xc9, 0x56, 0xe6, 0x1f, 0xf8, 0xdb, 0xfc, 0x55, 0x92,
	0x49, 0xe6, 0x23, 0x75, 0x1e, 0xea, 0xbe, 0xcd, 0xc9, 0x3d, 0xb9, 0xf7, 0x9c, 0x9b, 0x7b, 0x07,
	0x26, 0x92, 0xad, 0xb8, 0xd2, 0xb2, 0x9c, 0x6f, 0xa4, 0xd0, 0x02, 0xc5, 0x0d, 0xbe, 0x7a, 0x4a,
	0x9e, 0x43, 0xfc, 0xae, 0xe0, 0x3a, 0x65, 0x3f, 0xb7, 0x4c, 0x69, 0xf4, 0xd8, 0xb0, 0x37, 0x42,
	0x71, 0x2d, 0x64, 0xf9, 0x6d, 0x2b, 0x33, 0x1c, 0x4c, 0x83, 0xd9, 0x28, 0x1d, 0xb7, 0xa7, 0x9f,
	0x64, 0x46, 0x3e, 0xc2, 0x81, 0xbd, 0xa5, 0x36, 0xa2, 0x50, 0x0c, 0x1d, 0x41, 0xa4, 0x96, 0x97,
	0x2c, 0xa7, 0x15, 0x3d, 0x5e, 0xdc, 0x99, 0x77, 0x6a, 0xcc, 0xcf, 0xab, 0x50, 0xea, 0x28, 0xe8,
	0x10, 0x6e, 0x69, 0xb1, 0x66, 0x05, 0x1e, 0x54, 0xa9, 0x2d, 0x20, 0x47, 0x00, 0x67, 0xac, 0xd1,
	0xf1, 0x10, 0xc0, 0xb2, 0x3b, 0x1a, 0x46, 0xf6, 0xc4, 0xd4, 0x3f, 0x81, 0xb8, 0x22, 0xef, 0x50,
	0x9e, 0x7c, 0x81, 0xf1, 0xb9, 0xa6, 0x7a, 0xab, 0xea, 0x5a, 0xff, 0x25, 0x3e, 0x81, 0x61, 0x26,
	0x96, 0xeb, 0x0b, 0x9e, 0xb1, 0x4a, 0xff, 0x41, 0xda, 0x60, 0xf2, 0x1a, 0x26, 0x75, 0x66, 0x27,
	0xec, 0x09, 0x0c, 0x7f, 0x51, 0x59, 0xf0, 0x62, 0xa5, 0x70, 0x30, 0x0d, 0x67, 0xf1, 0xe2, 0xd0,
	0x4b, 0xfe, 0xd9, 0x06, 0xd3, 0x86, 0x45, 0xbe, 0xc2, 0xf8, 0x8d, 0xc8, 0x73, 0x7e, 0xc3, 0x4e,
	0xf4, 0x37, 0xd3, 0x9c, 0x5e, 0x08, 0xb9, 0x64, 0x38, 0x9c, 0x06, 0xb3, 0x61, 0x6a, 0x01, 0x11,
	0x30, 0xa9, 0x73, 0xef, 0xf2, 0x6e, 0x5d, 0x33, 0x83, 0x1b, 0x99, 0x79, 0x09, 0xfb, 0xee, 0xd0,
	0xf4, 0xcd, 0xf4, 0x68, 0x43, 0xf5, 0xa5, 0x33, 0xd1, 0x60, 0x84, 0x61, 0x3f, 0x67, 0x4a, 0xd1,
	0x15, 0x73, 0x2e, 0x6a, 0x48, 0xfe, 0x04, 0x10, 0x59, 0x15, 0xe8, 0x36, 0x84, 0x6d, 0x03, 0xcc,
	0x27, 0xba, 0x0b, 0x91, 0x90, 0x7c, 0xc5, 0x6b, 0xef, 0x0e, 0x79, 0x4f, 0x14, 0xfa, 0x4f, 0x84,
	0x5e, 0xc0, 0x30, 0x67, 0x9a, 0xfe, 0xa0, 0x9a, 0xe2, 0xbd, 0xca, 0xc3, 0xa3, 0x1e, 0xcb, 0xf3,
	0xf7, 0x8e, 0xf3, 0xb6, 0xd0, 0xb2, 0x4c, 0x9b, 0x2b, 0xc9, 0x29, 0x8c, 0xbd, 0x90, 0x51, 0xb5,
	0x66, 0x65, 0xad, 0x6a, 0xcd, 0x4a, 0xd3, 0xfa, 0x2b, 0x9a, 0x6d, 0x6b, 0x2b, 0x16, 0x9c, 0x0c,
	0x8e, 0x83, 0xc5, 0xef, 0x01, 0x8c, 0x3e, 0x98, 0x0d, 0x34, 0x6a, 0xd0, 0x29, 0xec, 0x99, 0x15,
	0x42, 0xd8, 0xab, 0xdf, 0xd9, 0xc5, 0xe4, 0x7e, 0x4f, 0xc4, 0xbd, 0xdb, 0x31, 0x84, 0x67, 0x4c,
	0xa3, 0x7b, 0x1e, 0xa3, 0x5d, 0x9f, 0x04, 0xff, 0x1b, 0x70, 0x37, 0x5f, 0x41, 0x64, 0x67, 0x14,
	0x25, 0xbe, 0xf1, 0xee, 0x4a, 0x24, 0x0f, 0x7a, 0x63, 0x6d, 0x0a, 0x3b, 0x46, 0xd7, 0x52, 0x78,
	0x73, 0x7b, 0x2d, 0x85, 0x3f, 0x77, 0xdf, 0xa3, 0xea, 0x4f, 0xf4, 0xec, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x0d, 0x30, 0x2a, 0x9b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProtolockClient is the client API for Protolock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProtolockClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type protolockClient struct {
	cc *grpc.ClientConn
}

func NewProtolockClient(cc *grpc.ClientConn) ProtolockClient {
	return &protolockClient{cc}
}

func (c *protolockClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/registry.v1.Protolock/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protolockClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/registry.v1.Protolock/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protolockClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/registry.v1.Protolock/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protolockClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/registry.v1.Protolock/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtolockServer is the server API for Protolock service.
type ProtolockServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
}

func RegisterProtolockServer(s *grpc.Server, srv ProtolockServer) {
	s.RegisterService(&_Protolock_serviceDesc, srv)
}

func _Protolock_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtolockServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.v1.Protolock/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtolockServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Protolock_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtolockServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.v1.Protolock/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtolockServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Protolock_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtolockServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.v1.Protolock/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtolockServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Protolock_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtolockServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.v1.Protolock/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtolockServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Protolock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registry.v1.Protolock",
	HandlerType: (*ProtolockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Protolock_Init_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Protolock_Get_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Protolock_Status_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Protolock_Commit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
